spring:
  application:
    name: ai
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lpz
    password: lpz2003...
    url: jdbc:mysql://localhost:3306/ai
  # session失效时间，一天86400秒
  session:
    timeout: 86400
    store-type: redis
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 4
  jackson:
  #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    # mybatis 输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis 配置,取消下划线转驼峰
    map-underscore-to-camel-case: false
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值